#ifndef CO_CONFIG_SYSTEM_H__
#define CO_CONFIG_SYSTEM_H__

#define CO_CONFIG_PDO 0
#define CO_CONFIG_SYNC 0

#define CO_CONFIG_SDO_SRV          \
	(CO_CONFIG_SDO_SRV_SEGMENTED | \
	 CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE)

#define CO_CONFIG_SDO_SRV_BUFFER_SIZE 534

#endif // CO_CONFIG_SYSTEM_H__